// <auto-generated />
using System;
using MessangerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessangerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240130174039_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessangerApi.Data.Model.Message", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("integer");

                    b.Property<int>("StatusMessageStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Guid")
                        .HasName("message_pkey");

                    b.HasIndex("StatusMessageStatus");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("MessangerApi.Data.Model.Status", b =>
                {
                    b.Property<int>("MessageStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageStatus")
                        .HasName("status_pkey");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            MessageStatus = 0,
                            Name = "NotDelivered"
                        },
                        new
                        {
                            MessageStatus = 1,
                            Name = "Delivered"
                        });
                });

            modelBuilder.Entity("MessangerApi.Data.Model.Message", b =>
                {
                    b.HasOne("MessangerApi.Data.Model.Status", "Status")
                        .WithMany("Messages")
                        .HasForeignKey("StatusMessageStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MessangerApi.Data.Model.Status", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
